seed: [ 0 ]
n: [ 4000 ]
m: [ 100 ]
d: [ 2 ]
dataset: [ moons ]

meta_pred: [ simplenet ]

splits: [ [ 0.55, 0.20, 0.25 ] ]
pred_arch: [ [ 3 ] ]  # [[3], [7]]
comp_set_size: [0] # [ 0, 8, 15 ]

msg_size: [ 50 ] # [3, 5, 7, 10, 15, 20, 30, 50, 100]
ca_dim: [ [ 100 ] ] # [[100], [100, 100]]
kme_dim: [ [ 100 ] ] # [[100], [100, 100]]
mod_1_dim: [ [ 100 ] ]
mod_2_dim: [ [ 100 ] ] # [[100], [100, 50]]
tau: [ 20 ]
init: [ kaiming_unif ]
criterion: [ bce_loss ]

start_lr: [ 1e-2] # [ 1e-2, 1e-3 ]
pen_msg: [ l2 ]
pen_msg_coef: [ 0 ]
msg_type: [cnt] # [ dsc, cnt ]
batch_size: [ 200 ]

optimizer: [ adam ]
scheduler: [ plateau ]
patience: [ 100 ]
factor: [ 0.5 ]
tol: [ 1e-2 ]
early_stop: [ 100 ]

n_epoch: [ 2 ]
device: [ cpu ]
weightsbiases: [ [ graal_deeprm2024, deeprm_new ] ]