data_encoder_config_path: data_encoder/kme.yaml
dataset_config_path: dataset/moon.yaml
log_config_path: log/off.yaml
training_config_path: training/gpu.yaml

bound_computation: False

msg_type: cnt
msg_size: 100
msg_penalty: l1
msg_penalty_coef: 0

compression_set_size: 0
attention_dim: [0]
attention_temperature: 20

mlp_1_dim: [100]
mlp_2_dim: [100]
meta_pred: simple_net
pred_hidden_sizes: [3]

has_skip_connection: True
has_batch_norm: True

optimizer: adam
lr: 1e-2
early_stopping_patience: 75
early_stopping_tolerance: 1e-2

scheduler: plateau
scheduler_patience: 25
scheduler_factor: 0.5
scheduler_threshold: 1e-2

init_scheme: kaiming_unif
loss_exponent: 1.0