is_using_wandb: True
is_wandb_alert_activated: True
project_name: test
run_name_content: [msg_size, msg_type, n_dataset, pred_arch]

dataset: moon
is_moon_identical: True
is_blob_identical: True
shuffle_each_dataset_samples: True
balanced: True
splits: [0.55, 0.20, 0.25]
n_dataset: 1000
m: 100
d: 2

seed: 0

comp_set_size: 0
ca_dim: [100]
tau: 20

data_compressor_name: KME
data_compressor_dim: [100]
mod_1_dim: [100]

mod_2_dim: [100]
meta_pred: simplenet
pred_arch: [3]

has_skip_connection: True
has_batch_norm: True

init_scheme: kaiming_unif
criterion: bce_loss
loss_power: 1.0

msg_type: cnt
msg_size: 1000
pen_msg: l2
pen_msg_coef: 0

optimizer: adam
lr: 1e-3
scheduler: plateau
scheduler_patience: 20
factor: 0.5
scheduler_threshold: 1e-2

early_stopping_patience: 50
early_stopping_tolerance: 1e-2

n_epoch: 1000
batch_size: 200
device: gpu
