is_using_wandb: True
project_name: test
run_name_content: [msg_size, msg_type, n_dataset, pred_arch]

dataset: moons
splits: [0.55, 0.20, 0.25]
n_dataset: 4000
m: 100
d: 2

seed: 0

meta_pred: simplenet
pred_arch: [3]
comp_set_size: 0

ca_dim: [100]
dim_reducer_name: KME
dim_reducer_dim: [100]

mod_1_dim: [100]
mod_2_dim: [100]
tau: 20
init: kaiming_unif
criterion: bce_loss

msg_type: cnt
msg_size: 1000
pen_msg: l2
pen_msg_coef: 0

optimizer: adam
lr: 1e-3
scheduler: plateau
scheduler_patience: 5
factor: 0.5
scheduler_threshold: 1e-2

early_stopping_patience: 5
early_stopping_tolerance: 1e-2

n_epoch: 2
batch_size: 200
device: gpu
