is_using_wandb: [False]
project_name: [message_module_with_kme]
run_name_content: [msg_size, msg_type, n_dataset, pred_arch]

dataset: [MTPL2_frequency]
balanced: [False]
splits: [[0.55, 0.20, 0.25]]
n_dataset: [1000]
m: [1000]
d: [2]

seed: [0]

meta_pred: [simplenet]
pred_arch: [[20, 10]]
comp_set_size: [0]

ca_dim: [[0]]
kme_dim: [[200, 200, 200]]
mod_1_dim: [[1000]]
mod_2_dim: [[1000]]
tau: [20]

has_skip_connection: True
has_batch_norm: True

init_scheme: [kaiming_unif]
criterion: [bce_loss]
loss_power: [1]

msg_type: [cnt]
msg_size: [1000]
pen_msg: [l2]
pen_msg_coef: [0]
batch_size: [200]

optimizer: [adam]
lr: [1e-3]
scheduler: [plateau]
scheduler_patience: [50]
factor: [0.5]
scheduler_threshold: [1e-2]

early_stopping_patience: [100]
early_stopping_tolerance: [1e-2]

n_epoch: [50]
device: [cpu]
