dataset_config_path: dataset/mnist_17.yaml
log_config_path: log/off.yaml
training_config_path: training/gpu.yaml
compute_prior: True
max_prior_epoch: 1
posterior_handicap: 0.1

is_bound_computed: True
bound_computation_epoch_frequency: 10
is_media_computed: True

msg_type: dsc
msg_size: 10
msg_penalty: l2
msg_penalty_coef: 0
is_using_a_random_msg: False

data_encoder_name: kme
kme_dim: [100]
fs_pool_dim: [100]
conv_one_by_one_n_filters: 3
tfm_input_dim: 64
tfm_n_heads: 1
tfm_mlp_dim: 51
tfm_n_encoders: 1
tfm_drop_out: 0
tfm_output_dim: 10

compression_set_size: 0
attention_dim: [10]
attention_temperature: 20
attention_pooling_type: kme

module_1_dim: [100]
module_2_dim: [100]
meta_pred: simple_net
pred_hidden_sizes: [10]

has_skip_connection: True
has_batch_norm: True
batch_norm_min_dim: 0

optimizer: adam
lr: 1e-3
early_stopping_patience: 40
early_stopping_tolerance: 1e-2

scheduler: plateau
scheduler_patience: 20
scheduler_factor: 0.5
scheduler_threshold: 1e-2

init_scheme: kaiming_norm
loss_exponent: 1.0