data_encoder_config_path: data_encoder/kme.yaml
dataset_config_path: dataset/mnist.yaml
log_config_path: log/off.yaml
training_config_path: training/gpu.yaml

bound_computation: False

msg_type: cnt
msg_size: 10
pen_msg: l1
pen_msg_coef: 0

comp_set_size: 0
ca_dim: [0]
tau: 20

mod_1_dim: [100]
mod_2_dim: [100]
meta_pred: simplenet
pred_hidden_sizes: [3]

has_skip_connection: True
has_batch_norm: True

optimizer: adam
lr: 1e-2
early_stopping_patience: 75
early_stopping_tolerance: 1e-2

scheduler: plateau
scheduler_patience: 25
factor: 0.5
scheduler_threshold: 1e-2

init_scheme: kaiming_unif
loss_power: 1.0