dataset: [moons]
splits: [[0.55, 0.20, 0.25]]
n: [2000]
m: [100]
d: [2]

seed: [0]

meta_pred: [simplenet]
pred_arch: [[3]]
comp_set_size: [0]

msg_size: [100]
ca_dim: [[100, 100]]
kme_dim: [[100, 100]]
mod_1_dim: [[100]]
mod_2_dim: [[100, 50]]
tau: [20]
init: [kaiming_unif]
criterion: [bce_loss]

start_lr: [1e-3]
pen_msg: [l2]
pen_msg_coef: [0]
msg_type: [cnt]
batch_size: [200]

optimizer: [adam]
scheduler: [plateau]
scheduler_patience: [10]
factor: [0.5]
scheduler_threshold: [1e-2]

early_stopping_patience: [5]
early_stopping_tolerance: [5e-3]

n_epoch: [100]
device: [gpu]
weightsbiases: [[graal_deeprm2024, deeprm_new]]
