project_name: [you_can_delete_this_project]
run_name_content: [[has_skip_connection, has_batch_norm, lr]]

dataset: [moon]
msg_size: ${mod_1_dim[0]}
lr: [1e-2, 1e-3]
has_batch_norm: [True]
mod_1_dim:  [[50]]  # [[50], [100], [500], [1000]]
mod_2_dim:  ${mod_1_dim}
batch_size: [50]
n_epoch: [5]
