project_name: [test]
run_name_content: [[lr, module_1_dim, msg_type, msg_size, compression_set_size, pred_hidden_sizes, seed, msg_std]]

batch_size: [0]
meta_batch_size: [20]
lr: [1e-3]
seed: [0]

data_encoder_name: [deepset]
n_pixels_to_permute: [0]

module_1_dim: [[200, 200], [500, 500]]
module_2_dim: [[100], [200], [500, 500]]
deepset_dim: [[100], [200, 200]]
attention_dim: [[400, 400]]

msg_penalty: [l2]
msg_penalty_coef: [0]

msg_type: [dsc, cnt]
msg_std: [1]
msg_size: [0, 1, 2, 4, 8, 16, 32]
compression_set_size: [0, 1, 2, 4, 6, 8, 12]
compression_pool_size: [20]
pred_filter_sizes: [[10, 20]]
pred_hidden_sizes: [[200, 200]]