project_name: [message-module-with-kme-exp3]
run_name_content: [[msg_size, has_batch_norm, pred_hidden_sizes, batch_size, lr]]

msg_size: ${mod_1_dim[0]}
pred_hidden_sizes: [[3], [10]]
lr: [1e-2, 1e-3]
has_batch_norm: [False, True]
mod_1_dim:  [[50]]  # [[50], [100], [500], [1000]]
mod_2_dim:  ${mod_1_dim}
batch_size: [10, 50, 200]
