project_name: [testing_mnist_2]
run_name_content: [[lr, module_1_dim, msg_type, msg_size, compression_set_size, pred_hidden_sizes, seed, msg_std]]

batch_size: [20]
lr: [1e-3]
seed: [0]

data_encoder_name: [kme]
n_pixels_to_permute: [300]

module_1_dim: [[500, 500]]
module_2_dim: [[500, 500]]
kme_dim: [[500, 10]]
attention_dim: [[200]]

msg_penalty: [l2]
msg_penalty_coef: [0]

msg_type: [cnt]
msg_std: [1]
msg_size: [2]
compression_set_size: [0]
pred_filter_sizes: [[10, 20]]
pred_hidden_sizes: [[200, 200]]