project_name: [Skip_connection_and_batch_norm]
run_name_content: [[has_skip_connection, has_batch_norm, lr]]

dataset: [blob_and_moon]
msg_size: ${mod_1_dim[0]}
lr: [1e-2, 1e-3]
has_skip_connection: [False, True]
has_batch_norm: [False, True]
mod_1_dim:  [[50]]  # [[50], [100], [500], [1000]]
mod_2_dim:  ${mod_1_dim}
batch_size: [50]
n_epoch: [10]
