project_name: [image_encoder_on_cifar100]
run_name_content: [[lr, msg_type, msg_size, compression_set_size, is_concatenating_target_in_image_encoder]]

batch_size: [0]
meta_batch_size: [20]
lr: [1e-4]
seed: [1234]

data_encoder_name: [image_encoder]
is_concatenating_target_in_image_encoder: [True, False]

n_pixels_to_permute: [0]

module_1_dim: [[500, 500]]
module_2_dim: [[500, 500]]
kme_dim: [[500, 500]]
attention_dim: [[200]]

msg_penalty: [l2]
msg_penalty_coef: [0]

msg_type: [cnt]  # dsc
msg_std: [1]
msg_size: [4, 32]
compression_set_size: [0, 4, 16]
pred_filter_sizes: [[10, 20]]
pred_hidden_sizes: [[200, 200]]