project_name: [examples_selection_on_moon_9]
run_name_content: [[lr, msg_type, msg_size, compression_set_size, pred_hidden_sizes]]

batch_size: [10]
lr: [1e-3]

data_encoder_name: [kme]
n_pixels_to_permute: [0]

module_1_dim: [[1000]]
module_2_dim: [[1000]]
kme_dim: [[1000]]
attention_dim: [[100]]

msg_penalty: [l2]
msg_penalty_coef: [0]

msg_type: [dsc]
msg_size: [1]
compression_set_size: [0]
pred_hidden_sizes: [[500, 200]]
