is_using_wandb: [True]
project_name: [message_module_with_kme]
run_name_content: [msg_size, msg_type, n_dataset, pred_arch]

dataset: [moons]
splits: [[0.55, 0.20, 0.25]]
n_dataset: [200, 1000]
m: [100]
d: [2]

seed: [0]

meta_pred: [simplenet]
pred_arch: [[3], [3, 3], [5, 5, 5]]
comp_set_size: [0]

ca_dim: [[100]]
kme_dim: [[100]]
mod_1_dim: [[100]]
mod_2_dim: [[100]]
tau: [20]
init: [kaiming_unif]
criterion: [bce_loss]

msg_type: [dsc, cnt]
msg_size: [5, 10, 50, 100, 1000]
pen_msg: [l2]
pen_msg_coef: [0]
batch_size: [200]

optimizer: [adam]
lr: [1e-2, 1e-3]
scheduler: [plateau]
scheduler_patience: [10]
factor: [0.1]
scheduler_threshold: [5e-3]

early_stopping_patience: [10]
early_stopping_tolerance: [5e-3]

n_epoch: [200]
device: [gpu]
