dataset: cifar100

task: classification
target_size: 1
criterion: bce_loss
is_dataset_balanced: True
splits: [0.5, 0.17, 0.33]
shuffle_each_dataset_samples: True

n_dataset: 150
n_data_per_train_dataset: 1200
n_data_per_test_dataset: 200
input_shape: [3, 32, 32]  # [3, 32, 32], [3, 15, 15]
n_features: 3072  # 3072, 675

is_encoding_as_images: True