dataset: cifar100_binary

task: classification
target_size: 1
criterion: bce_loss
is_dataset_balanced: True
splits: [0.55, 0.20, 0.25]
shuffle_each_dataset_samples: True
are_test_classes_shared_with_train: False

n_dataset: 240
n_instances_per_dataset: 400
input_shape: [3, 15, 15]  # [3, 32, 32], [3, 15, 15]
n_features: 675  # 3072, 675