dataset: mnist_binary

task: classification
target_size: 1
criterion: bce_loss
is_dataset_balanced: True
splits: [0.48, 0.15, 0.37]
shuffle_each_dataset_samples: True

n_dataset: 90
n_data_per_train_dataset: 2000
n_data_per_test_dataset: 2000
n_features: 784

n_pixels_to_permute: 0
is_encoding_as_images: True