dataset: mnist

task: classification
target_size: 1
criterion: bce_loss
is_dataset_balanced: True
splits: [0.55, 0.20, 0.25]
shuffle_each_dataset_samples: True

n_dataset: 90
n_instances_per_dataset: 100
n_features: 49
