dataset: mnist_label_shuffle

task: classification
target_size: 10
criterion: ce_loss
is_dataset_balanced: True
splits: [0.645, 0.105, 0.25]
shuffle_each_dataset_samples: True
n_pixels_to_permute: 0

n_dataset: 80
n_data_per_train_dataset: 1000
n_data_per_test_dataset: 100
n_features: 784

is_encoding_as_images: True

# 10 training tasks of 60'000 examples
# 20 test     tasks of  2'000 examples
# ------------------------------------
# 640'000: -Train prop.: 0.9375
#          -Test  prop.: 0.0625
#
# In practice: 320 tasks of 2000 examples
#           or 640 tasks of 1000 examples.


# 10 training tasks of 600 examples
# 20 test     tasks of 100 examples
# ------------------------------------
# 8000: -Train prop.: 0.80
#       -Test  prop.: 0.20
#
# In practice: 80 tasks of 100 examples
#           or 40 tasks of 200 examples.