dataset: mnist

task: classification
target_size: 10
criterion: ce_loss
is_dataset_balanced: True
splits: [0.7875, 0.15, 0.0625]
shuffle_each_dataset_samples: True
n_pixels_to_permute: 200

n_dataset: 320
n_data_per_train_dataset: 2000
n_data_per_test_dataset: 2000
input_shape: [1, 28, 28]
n_features: 784

is_encoding_as_images: True