dataset: mnist_label_shuffle

task: classification
target_size: 10
criterion: ce_loss
is_dataset_balanced: True
splits: [0.6, 0.15, 0.25]
shuffle_each_dataset_samples: True
n_pixels_to_permute: 0

n_dataset: 40
n_data_per_train_dataset: 1000
n_data_per_test_dataset: 100
n_features: 784

is_encoding_as_images: True