dataset: mnist_multi

task: classification
target_size: 10
criterion: ce_loss
is_dataset_balanced: True
splits: [0.55, 0.20, 0.25]
shuffle_each_dataset_samples: True
n_pixels_to_permute: 0

n_dataset: 640
n_instances_per_dataset: 1000
n_features: 784
