dataset: moon

task: classification
target_size: 1
criterion: bce_loss
is_dataset_balanced: True
splits: [0.55, 0.20, 0.25]
shuffle_each_dataset_samples: True

is_moon_identical: False

n_dataset: 400
n_instances_per_dataset: 200
n_features: 2

is_encoding_as_images: False
