dataset: MTPL2_frequency  # MTPL2_frequency, MTPL2_severity, MTPL2_pure

task: regression
criterion: mse_loss
balanced: False
splits: [0.55, 0.20, 0.25]
shuffle_each_dataset_samples: True

n_dataset: 200
n_instances_per_dataset: 100
n_features: 76